// registration
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const REQUEST_SIGN_IN_SUCCESS = 'REQUEST_SIGN_IN_SUCCESS';
export const REQUEST_SIGN_IN_FAILED = 'REQUEST_SIGN_IN_FAILED';
export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';
export const REQUEST_SIGN_OUT_SUCCESS = 'REQUEST_SIGN_OUT_SUCCESS';
export const REQUEST_SIGN_OUT_FAILED = 'REQUEST_SIGN_OUT_FAILED';
