// registration
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const REQUEST_SIGN_IN_SUCCESS = 'REQUEST_SIGN_IN_SUCCESS';
export const REQUEST_SIGN_IN_FAILED = 'REQUEST_SIGN_IN_FAILED';
export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';
export const REQUEST_SIGN_OUT_SUCCESS = 'REQUEST_SIGN_OUT_SUCCESS';
export const REQUEST_SIGN_OUT_FAILED = 'REQUEST_SIGN_OUT_FAILED';
export const LOAD_ALL_NEWS = 'LOAD_ALL_NEWS';
export const LOAD_ALL_NEWS_SUCCESS = 'LOAD_ALL_NEWS_SUCCESS';
export const LOAD_ALL_NEWS_FAILED = 'LOAD_ALL_NEWS_FAILED';
